AWS_ACCESS_KEY_ID: [YOUR_KEY_HERE]
AWS_SECRET_ACCESS_KEY: [YOUR_KEY_HERE]
development:
  SENDGRID_USERNAME: "YOUR_USERNAME_HERE"
  SENDGRID_PASSWORD: "YOUR_PASSWORD_HERE"
  AWS_BUCKET: bucket-name-here
production:
  AWS_BUCKET: bucket-name-here